"""EPS protocol constants used by bridge and emulator."""

from __future__ import annotations

EPS_SIMULATOR_NODE_ID = 1
EPS_HOUSEKEEPING_PAYLOAD_LEN = 19
EPS_MAX_REPLY_FRAMES = 4

EPS_FLAG_SAFE_MODE = 0x0001
EPS_FLAG_LOW_BATTERY = 0x0002
EPS_FLAG_OVERTEMP = 0x0004
EPS_FLAG_PANEL_FAULT = 0x0008
EPS_FLAG_BATTERY_DEGRADED = 0x0010
EPS_FLAG_OVERCURRENT = 0x0020
EPS_FLAG_PAYLOAD_SHED = 0x0040

AETHERFLOWCAN_SERVICE_HOUSEKEEPING = 3
AETHERFLOWCAN_SERVICE_PARAMETER = 20
AETHERFLOWCAN_HK_SUBTYPE_REPORT = 25
AETHERFLOWCAN_HK_SUBTYPE_CRITICAL_REPORT = 26
AETHERFLOWCAN_PARAMETER_SUBTYPE_GET = 1
AETHERFLOWCAN_PARAMETER_SUBTYPE_SET = 2
AETHERFLOWCAN_PARAMETER_SUBTYPE_VALUE = 3
